### ISSUE TITLE
Open Image after inserting it

### ISSUE THREAD

**Issue by tomasmaks** [xmuSistone/android-animate-RichEditor#11]
Thank you for these great repository! It is the best editor for android I found on github.
One more thing, It would be also nice to know. How is it possible to implement that after we insert image in this editor, we would be able to open it in the gallery?
Thank you in advance.

**Comment by xmuSistone** [comment]
DataImageView has saved the imagePath, u can traverse the itemViews and pick up all the images' path and send them to your gallery (maybe it cannot be called gallery, just ViewPager do that thing).
