### ISSUE TITLE
Publish the demo APK on Google Play

### ISSUE THREAD

**Issue by quentin-st** [xmuSistone/android-animate-RichEditor#2]
This library looks great, but you only provide an APK file to try it out.
It would be great to be able to download the app straight from Google Play to test the app!

Plus, you can benefit from [GitHub's releases feature](https://github.com/xmuSistone/android-animate-RichEditor/releases) in order to publish generated APK associated with releases.

**Comment by xmuSistone** [comment]
Sorry to tell you that i m at China and Google play is not available at my network.

**Comment by quentin-st** [comment]
This is indeed a good reason to not publish it, sorry to hear that!
