### ISSUE TITLE
Licence is missing

### ISSUE THREAD

**Issue by quentin-st** [xmuSistone/android-animate-RichEditor#3]
This project does not have any licence information.

GitHub helps project owners to chose the right licence, check [Open source licensing](https://help.github.com/articles/open-source-licensing/) page and [choosealicense.com](http://choosealicense.com/)!

As quoted from this page:

> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

**Comment by xmuSistone** [comment]
Ok, I've copied some related license from other project. thanks for notify me that.
