### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by txlbupt** [xmuSistone/android-animate-RichEditor#4]
添加多张图片时可能出现OutOfMemoryError

**Comment by xmuSistone** [comment]
代码中没有管理好Bitmap，你考虑用Universal Image Loader来加载图片吧。暂时这个项目不会引入新的jar了。

**Comment by txlbupt** [comment]
比较困惑的是为什么用scrollview实现，而不是用listview实现呢

**Comment by xmuSistone** [comment]
因为listview涉及view复用，view高度的管理比较混乱，所以当时没考虑用listview

**Comment by txlbupt** [comment]
如果不服用的话。是不是可能view太多了会把内存撑爆呢？ 发自网易邮箱大师 在2015年12月21日 11:43 ，sistone写道： 因为listview涉及view复用，view高度的管理比较混乱，所以当时没考虑用listview — Reply to this email directly or view it on GitHub.

**Comment by xmuSistone** [comment]
scrollview没有你想象中那么脆弱。如果是view太多导致了oom，一方面要从代码优化找原因，另一方面也得考虑你们的产品设计是不是不科学了
