### ISSUE TITLE
怎么样把服务器拿下来的数据显示到editor里面？

### ISSUE THREAD

**Issue by HarryF514** [xmuSistone/android-animate-RichEditor#5]
把已经有的数据显示出来，有没有接口？急，在线等

**Comment by xmuSistone** [comment]
由于该项目暂未引入Universal Image Loader图片下载的jar包，所以暂时不支持Editor显示网络数据。后面我会把你的这一需求特性加上，但是要等一段时间，因为公司的项目暂时有些吃紧。如果你比较着急的话，就自己加上吧，里面的逻辑不算太复杂的。

**Comment by HarryF514** [comment]
好的好的
