### ISSUE TITLE
add video?

### ISSUE THREAD

**Issue by sirvon** [xmuSistone/android-animate-RichEditor#6]
how bout adding video to the editor?

**Comment by xmuSistone** [comment]
Sorry to tell u that current version does not support adding videos. But, if u digest the file RichTextEditor.java, you can easily extend the function of this editor. As you can see, editor elements are distinguished by using "instanceof". However, elements can also be recognized by getting tags. 
To keep this editor simple and easily read, further extensions will not be added to this project, but i will be thankful if you add some creative features to new branches.

**Comment by xmuSistone** [comment]
while reviewing the source code, please neglect the Chinese annotations.
