### ISSUE TITLE
请问保存后怎么编辑呢？

### ISSUE THREAD

**Issue by sendtion** [xmuSistone/android-animate-RichEditor#7]
我编写图文后，保存到本地数据库，然后打开编辑，发现编辑后的原来的图片不能保存，新插入的可以

**Comment by sendtion** [comment]
问题解决了，还有个问题，怎么才能删除图片的时候，把保存在本地的图片也删除？

**Comment by xmuSistone** [comment]
文件路径已经保存，删除文件就好~
