### ISSUE TITLE
怎样才能得到输入的所有内容并转化为html类型的文本

### ISSUE THREAD

**Issue by liulinsen** [xmuSistone/android-animate-RichEditor#9]

**Comment by xmuSistone** [comment]
遍历所有子View，取出数据

**Comment by liulinsen** [comment]
如果转为html文本了 ，我保存草稿，下次再编辑怎么解

**Comment by xmuSistone** [comment]
不建议转为Html。数据与UI分离，一份数据，既可以在IOS用，又可以在安卓用，也能在PC用。怎么方便怎么来，你需要跟后端沟通好。
如果非要存储HTML，则HTML的解析工作，需要根据你生成的规则反向进行，往往会更麻烦。

**Comment by liulinsen** [comment]
如果不转，怎样来保存草稿和编辑草稿，再编辑的时候需要将保存的数据解析出来并在页面上呈现出原来的样子，这个不好解决吧

**Comment by xmuSistone** [comment]
我更推荐其它的方式。
HTML往往是标签太多，不便于操作。你可以考虑xml的形式，java里面也有专门的parser类可以用。存储的时候，并没有太大限制，性能、效率、可读性也都比html强一些。-仅供参考

**Comment by liulinsen** [comment]
你写的这个编辑器能解析富文本数据吗

**Comment by xmuSistone** [comment]
@liulinsen 用json吧，json通用性比较好

**Comment by xmuSistone** [comment]
数据格式都没定，怎么解析富文本。现在不支持的，要依赖于数据格式，是json还是xml，还是html

**Comment by xmuSistone** [comment]
如果你定好了格式，这个会很简单的。代码本身就那几行，初入行三五个月的都能看懂的

**Comment by liulinsen** [comment]
我研究一下吧，非常感谢

**Comment by shallowlight** [comment]
我刚好用这个做过一次，草稿什么的也都做了，但是并未用到html，当时是将表单数据存储到java bean,然后转为json，以字符串形式保存到sd卡上的文件中。

**Comment by is1988** [comment]
@liulinsen 我们现在有个需求和知乎差不多 但现在不实现编辑 只实现发布 所以也要将内容转换成html后以post形式发给服务器 目前是选择一张图就上传一次到服务器然后获取对应的imageName 你那有好的解决方案吗 我指的是转换html标签
